language: swift

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode10.1

env:
  - FIXTURE_PATH_SIMPLE=./Fixtures/simple/mock-config.yml

install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then ./scripts/install_swift.sh; fi


script:
  - swiftlint
  - swift build
  - swift test